apiVersion: v1
kind: Pod
metadata:
  name: ssh
spec:
  containers:
    - name: ssh
      image: corbinu/ssh-server
      volumeMounts:
        - name: home
          mountPath: /mnt/home
        - name: ssh-key
          mountPath: /root/ssh-key
      ports:
        - containerPort: 22
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "cat /root/ssh-key/id_rsa.pub >> /root/.ssh/authorized_keys"]
  volumes:
    - name: home
      hostPath:
        path: /dfs/home
    - name: ssh-key
      secret:
        secretName: my-ssh-public-key
        defaultMode: 256
